# Generated by Django 4.1 on 2022-08-25 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_foods', '0003_food_description'),
        ('app_general', '0002_subscription_food'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='food',
        ),
        migrations.AddField(
            model_name='subscription',
            name='food_set',
            field=models.ManyToManyField(to='app_foods.food'),
        ),
    ]
